name: devschool_course_management
services:
  app:
    build: ./
    container_name: devschool_course_management-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/devschooldb
  db:
    image: mysql
    container_name: devschool_course_management_db
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: P@55w0rd
      MYSQL_USER: course_management
      MYSQL_PASSWORD: P@55w0rd
      MYSQL_DATABASE: devschooldb
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 3s
      timeout: 3s
      retries: 3